/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as GoldEmiRouteImport } from './routes/gold-emi'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BuyGoldRouteImport } from './routes/buy-gold'
import { Route as BusinessModelRouteImport } from './routes/business-model'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterPartnerRouteImport } from './routes/register.partner'
import { Route as RegisterCustomerRouteImport } from './routes/register.customer'
import { Route as PortalPartnerRouteImport } from './routes/portal.partner'
import { Route as PortalCustomerRouteImport } from './routes/portal.customer'
import { Route as DashboardPartnerRouteImport } from './routes/dashboard.partner'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as DashboardBranchRouteImport } from './routes/dashboard.branch'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as PartnerBranchesIndexRouteImport } from './routes/partner.branches.index'
import { Route as CustomerShopIndexRouteImport } from './routes/customer.shop.index'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin.catalog.index'
import { Route as PartnerBranchesBranchIdRouteImport } from './routes/partner.branches.$branchId'
import { Route as CustomerShopProductIdRouteImport } from './routes/customer.shop.$productId'
import { Route as AdminPartnersPartnerIdRouteImport } from './routes/admin.partners.$partnerId'
import { Route as AdminCatalogProductIdRouteImport } from './routes/admin.catalog.$productId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldEmiRoute = GoldEmiRouteImport.update({
  id: '/gold-emi',
  path: '/gold-emi',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyGoldRoute = BuyGoldRouteImport.update({
  id: '/buy-gold',
  path: '/buy-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModelRoute = BusinessModelRouteImport.update({
  id: '/business-model',
  path: '/business-model',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPartnerRoute = RegisterPartnerRouteImport.update({
  id: '/register/partner',
  path: '/register/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCustomerRoute = RegisterCustomerRouteImport.update({
  id: '/register/customer',
  path: '/register/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPartnerRoute = PortalPartnerRouteImport.update({
  id: '/portal/partner',
  path: '/portal/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCustomerRoute = PortalCustomerRouteImport.update({
  id: '/portal/customer',
  path: '/portal/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPartnerRoute = DashboardPartnerRouteImport.update({
  id: '/dashboard/partner',
  path: '/dashboard/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBranchRoute = DashboardBranchRouteImport.update({
  id: '/dashboard/branch',
  path: '/dashboard/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerBranchesIndexRoute = PartnerBranchesIndexRouteImport.update({
  id: '/partner/branches/',
  path: '/partner/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerShopIndexRoute = CustomerShopIndexRouteImport.update({
  id: '/customer/shop/',
  path: '/customer/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/admin/catalog/',
  path: '/admin/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerBranchesBranchIdRoute = PartnerBranchesBranchIdRouteImport.update({
  id: '/partner/branches/$branchId',
  path: '/partner/branches/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerShopProductIdRoute = CustomerShopProductIdRouteImport.update({
  id: '/customer/shop/$productId',
  path: '/customer/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersPartnerIdRoute = AdminPartnersPartnerIdRouteImport.update({
  id: '/$partnerId',
  path: '/$partnerId',
  getParentRoute: () => AdminPartnersRoute,
} as any)
const AdminCatalogProductIdRoute = AdminCatalogProductIdRouteImport.update({
  id: '/admin/catalog/$productId',
  path: '/admin/catalog/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/business-model': typeof BusinessModelRoute
  '/buy-gold': typeof BuyGoldRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold-emi': typeof GoldEmiRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/partners': typeof AdminPartnersRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/branch': typeof DashboardBranchRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/partner': typeof DashboardPartnerRoute
  '/portal/customer': typeof PortalCustomerRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/partner': typeof RegisterPartnerRoute
  '/admin/catalog/$productId': typeof AdminCatalogProductIdRoute
  '/admin/partners/$partnerId': typeof AdminPartnersPartnerIdRoute
  '/customer/shop/$productId': typeof CustomerShopProductIdRoute
  '/partner/branches/$branchId': typeof PartnerBranchesBranchIdRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/customer/shop/': typeof CustomerShopIndexRoute
  '/partner/branches/': typeof PartnerBranchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/business-model': typeof BusinessModelRoute
  '/buy-gold': typeof BuyGoldRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold-emi': typeof GoldEmiRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/partners': typeof AdminPartnersRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/branch': typeof DashboardBranchRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/partner': typeof DashboardPartnerRoute
  '/portal/customer': typeof PortalCustomerRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/partner': typeof RegisterPartnerRoute
  '/admin/catalog/$productId': typeof AdminCatalogProductIdRoute
  '/admin/partners/$partnerId': typeof AdminPartnersPartnerIdRoute
  '/customer/shop/$productId': typeof CustomerShopProductIdRoute
  '/partner/branches/$branchId': typeof PartnerBranchesBranchIdRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/customer/shop': typeof CustomerShopIndexRoute
  '/partner/branches': typeof PartnerBranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/business-model': typeof BusinessModelRoute
  '/buy-gold': typeof BuyGoldRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold-emi': typeof GoldEmiRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/partners': typeof AdminPartnersRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/branch': typeof DashboardBranchRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/partner': typeof DashboardPartnerRoute
  '/portal/customer': typeof PortalCustomerRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/register/customer': typeof RegisterCustomerRoute
  '/register/partner': typeof RegisterPartnerRoute
  '/admin/catalog/$productId': typeof AdminCatalogProductIdRoute
  '/admin/partners/$partnerId': typeof AdminPartnersPartnerIdRoute
  '/customer/shop/$productId': typeof CustomerShopProductIdRoute
  '/partner/branches/$branchId': typeof PartnerBranchesBranchIdRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/customer/shop/': typeof CustomerShopIndexRoute
  '/partner/branches/': typeof PartnerBranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/business-model'
    | '/buy-gold'
    | '/careers'
    | '/contact'
    | '/forgot-password'
    | '/gold-emi'
    | '/leadership'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/partners'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/customer'
    | '/dashboard/partner'
    | '/portal/customer'
    | '/portal/partner'
    | '/register/customer'
    | '/register/partner'
    | '/admin/catalog/$productId'
    | '/admin/partners/$partnerId'
    | '/customer/shop/$productId'
    | '/partner/branches/$branchId'
    | '/admin/catalog/'
    | '/customer/shop/'
    | '/partner/branches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/business-model'
    | '/buy-gold'
    | '/careers'
    | '/contact'
    | '/forgot-password'
    | '/gold-emi'
    | '/leadership'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/partners'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/customer'
    | '/dashboard/partner'
    | '/portal/customer'
    | '/portal/partner'
    | '/register/customer'
    | '/register/partner'
    | '/admin/catalog/$productId'
    | '/admin/partners/$partnerId'
    | '/customer/shop/$productId'
    | '/partner/branches/$branchId'
    | '/admin/catalog'
    | '/customer/shop'
    | '/partner/branches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/business-model'
    | '/buy-gold'
    | '/careers'
    | '/contact'
    | '/forgot-password'
    | '/gold-emi'
    | '/leadership'
    | '/login'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/partners'
    | '/dashboard/admin'
    | '/dashboard/branch'
    | '/dashboard/customer'
    | '/dashboard/partner'
    | '/portal/customer'
    | '/portal/partner'
    | '/register/customer'
    | '/register/partner'
    | '/admin/catalog/$productId'
    | '/admin/partners/$partnerId'
    | '/customer/shop/$productId'
    | '/partner/branches/$branchId'
    | '/admin/catalog/'
    | '/customer/shop/'
    | '/partner/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  BusinessModelRoute: typeof BusinessModelRoute
  BuyGoldRoute: typeof BuyGoldRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoldEmiRoute: typeof GoldEmiRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPartnersRoute: typeof AdminPartnersRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBranchRoute: typeof DashboardBranchRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardPartnerRoute: typeof DashboardPartnerRoute
  PortalCustomerRoute: typeof PortalCustomerRoute
  PortalPartnerRoute: typeof PortalPartnerRoute
  RegisterCustomerRoute: typeof RegisterCustomerRoute
  RegisterPartnerRoute: typeof RegisterPartnerRoute
  AdminCatalogProductIdRoute: typeof AdminCatalogProductIdRoute
  CustomerShopProductIdRoute: typeof CustomerShopProductIdRoute
  PartnerBranchesBranchIdRoute: typeof PartnerBranchesBranchIdRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
  CustomerShopIndexRoute: typeof CustomerShopIndexRoute
  PartnerBranchesIndexRoute: typeof PartnerBranchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-emi': {
      id: '/gold-emi'
      path: '/gold-emi'
      fullPath: '/gold-emi'
      preLoaderRoute: typeof GoldEmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-gold': {
      id: '/buy-gold'
      path: '/buy-gold'
      fullPath: '/buy-gold'
      preLoaderRoute: typeof BuyGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-model': {
      id: '/business-model'
      path: '/business-model'
      fullPath: '/business-model'
      preLoaderRoute: typeof BusinessModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/partner': {
      id: '/register/partner'
      path: '/register/partner'
      fullPath: '/register/partner'
      preLoaderRoute: typeof RegisterPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/customer': {
      id: '/register/customer'
      path: '/register/customer'
      fullPath: '/register/customer'
      preLoaderRoute: typeof RegisterCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/partner': {
      id: '/portal/partner'
      path: '/portal/partner'
      fullPath: '/portal/partner'
      preLoaderRoute: typeof PortalPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/customer': {
      id: '/portal/customer'
      path: '/portal/customer'
      fullPath: '/portal/customer'
      preLoaderRoute: typeof PortalCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/partner': {
      id: '/dashboard/partner'
      path: '/dashboard/partner'
      fullPath: '/dashboard/partner'
      preLoaderRoute: typeof DashboardPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/branch': {
      id: '/dashboard/branch'
      path: '/dashboard/branch'
      fullPath: '/dashboard/branch'
      preLoaderRoute: typeof DashboardBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/branches/': {
      id: '/partner/branches/'
      path: '/partner/branches'
      fullPath: '/partner/branches/'
      preLoaderRoute: typeof PartnerBranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/shop/': {
      id: '/customer/shop/'
      path: '/customer/shop'
      fullPath: '/customer/shop/'
      preLoaderRoute: typeof CustomerShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/admin/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/branches/$branchId': {
      id: '/partner/branches/$branchId'
      path: '/partner/branches/$branchId'
      fullPath: '/partner/branches/$branchId'
      preLoaderRoute: typeof PartnerBranchesBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/shop/$productId': {
      id: '/customer/shop/$productId'
      path: '/customer/shop/$productId'
      fullPath: '/customer/shop/$productId'
      preLoaderRoute: typeof CustomerShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners/$partnerId': {
      id: '/admin/partners/$partnerId'
      path: '/$partnerId'
      fullPath: '/admin/partners/$partnerId'
      preLoaderRoute: typeof AdminPartnersPartnerIdRouteImport
      parentRoute: typeof AdminPartnersRoute
    }
    '/admin/catalog/$productId': {
      id: '/admin/catalog/$productId'
      path: '/admin/catalog/$productId'
      fullPath: '/admin/catalog/$productId'
      preLoaderRoute: typeof AdminCatalogProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPartnersRouteChildren {
  AdminPartnersPartnerIdRoute: typeof AdminPartnersPartnerIdRoute
}

const AdminPartnersRouteChildren: AdminPartnersRouteChildren = {
  AdminPartnersPartnerIdRoute: AdminPartnersPartnerIdRoute,
}

const AdminPartnersRouteWithChildren = AdminPartnersRoute._addFileChildren(
  AdminPartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  BusinessModelRoute: BusinessModelRoute,
  BuyGoldRoute: BuyGoldRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoldEmiRoute: GoldEmiRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPartnersRoute: AdminPartnersRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBranchRoute: DashboardBranchRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardPartnerRoute: DashboardPartnerRoute,
  PortalCustomerRoute: PortalCustomerRoute,
  PortalPartnerRoute: PortalPartnerRoute,
  RegisterCustomerRoute: RegisterCustomerRoute,
  RegisterPartnerRoute: RegisterPartnerRoute,
  AdminCatalogProductIdRoute: AdminCatalogProductIdRoute,
  CustomerShopProductIdRoute: CustomerShopProductIdRoute,
  PartnerBranchesBranchIdRoute: PartnerBranchesBranchIdRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
  CustomerShopIndexRoute: CustomerShopIndexRoute,
  PartnerBranchesIndexRoute: PartnerBranchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
